{% set name = "shortcutter" %}
{% set version = "0.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1221ee4297fa46127cc66d7d908b1f3715c27b0da172711c00244e0260988bbe

build:
  number: 0
  entry_points:
    - shortcutter = shortcutter:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pywin32  # [win]

test:
  imports:
    - shortcutter
  commands:
    - shortcutter --help
    - shortcutter -t
    - shortcutter python

about:
  home: https://github.com/kiwi0fruit/shortcutter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Easy cross-platform creation of shortcuts supporting virtual and Anaconda environments (fork of Shortcut)'
  doc_url: https://github.com/kiwi0fruit/shortcutter
  dev_url: https://github.com/kiwi0fruit/shortcutter

extra:
  recipe-maintainers:
    - kiwi0fruit
