travis:
  secure:
    BINSTAR_TOKEN: kAe619+ZV0p0vmClpZURJODkBf/DM8PwVhEY/wX5J1pLXupOBBjnOaHHCEgd5lr165uAygvT1SkplZkYx4/LbSCE6Pz7SOA+Mwgpu6xbZYGCwFfmm7z5ujAB+n2roDBXG/e/6noFPbdjKxs1Zxso/vb1M7eDhUQ1HGowlv4F/BAV6RK3RYalPgJhry+nDKThR0cLBUK7HrNaDZc45MuQz7XyUjz/QyEUp5XrWjuvaTgC2jVxQ+y6uPDlXw5jPFnivUMqcaxL7mSs8KzKt5hc33WZvJ1KmKbeoFRzAsDiU6O2pOsNsbwRa9NjA5ikFFOZyLaIUxM3e69+LEKw2BzAwj5fccpLfW8hhVTKBCl418ozkGoK4T/lZEPeYq3TypXccmL5Mq5Z2FUh2XqOaPrjySiEJTFANLsVUanO3Xw+jMyAKyr98Batp7oIRwK8U71x7PxCz/3a04STK4O3JVDTfiIaMbzSSX70aerUhpbLz8q9I4kGeVtcAB8A9dOwH+mh5+iftgH6WlurgSjJssnC49PQOJJBzD01DW0D8Z+4BFYmYsqu9Zddczzi7GnwI2EUx85Og9g3BxZMRCROvYKYcpJu+/6L7nhDh8q/8UGVU+E86AfJcMrlB5CwTtQriS4nez5Dr0H+K8l19nyVDtWCWuQH9WaA/TETwl8fUGXi8uM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
