travis:
  secure:
    BINSTAR_TOKEN: IQgY69wSLrwU0tcapGzQ1DayFpo6DxZAb1J+swIkwpEBz5Bgqdi6oIsAaM0MgqDJdDUBGmWGbQ0WKa4vySeZ6NNP65gzoNkl1+FI2StYrig/ENk2uqJZZAP2CA7oC5pj/lR+y00yPVgU+2EFHx+Fdos8anfXa65gdhlByJ9CbkogskPZG97vy5c90R22yRt48VRBlw7BZLBsqnw47nNcmi+1NeUgcFtp0ZXuw0p1W65vsG0P1DKaakgOOvhQ2vbGzQO6qeAYiktd2lPZBXN8OKHYyvvaoEElj8SYQ0vQ68Aw8H5b8IGBlCSnAlzR+1vuBl0lf7RoTE3g1jJn3jkU8nlyloHH2U7ARGNZj36bKHXoiFZ5pn75pQlUJCcTuPOld9BwDdEsSCMTg8C3nHdPA+UFU3mty5dyhvHNsqzVvhpuchRZi9hjQ9yb/Irk6PUMP4kAmcg0J9RRpbEwyDBC/H1Zw+RcsMODZ2p6sM1StWshrXFXmm5XCRUg78sH9t/cDY+YNAAFDBDlzLJDh9J+5zRbsgJWei1AWc2aTQoSah5WNixjTXgKsyJaiPTh9MyhvoUmfRe7+hCIw5b3HBYWhwSuQQ1z6BRfTznAW3PaeqlBbcCMMaVJjrE9iGMGFvca8RQO4S22rj11r+Un6Yy5reLbbwyPmXHtVmG51l21Y5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
